# Generated by Django 3.1.5 on 2021-01-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_is_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
