# Generated by Django 3.1.5 on 2021-01-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_poster',
            new_name='poster_image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='title',
        ),
    ]
