# Generated by Django 3.1.5 on 2021-01-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210115_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_nominee',
            field=models.BooleanField(default=False),
        ),
    ]
